name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please fill out the form below to help us understand your request.

  - type: checkboxes
    id: existing-issues
    attributes:
      label: Prerequisites
      description: Please confirm the following before submitting
      options:
        - label: I have searched existing issues to ensure this feature hasn't been requested
          required: true

  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Type
      description: What type of feature is this?
      options:
        - New Agent
        - Agent Enhancement
        - New Provider
        - CLI Enhancement
        - Configuration Option
        - Documentation
        - Performance Improvement
        - Developer Experience
        - Integration
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Describe the problem this feature would solve
      placeholder: |
        I'm trying to [accomplish X], but currently [limitation Y] prevents me from doing so effectively...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your proposed solution
      placeholder: |
        I would like to see [feature] that allows [capability]...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What alternatives have you considered?
      placeholder: |
        I've tried [alternative approach] but it doesn't work because...

  - type: textarea
    id: api-design
    attributes:
      label: API Design (Optional)
      description: If you have ideas for the API, share them here
      render: python
      placeholder: |
        # Example API usage
        from adversarial_debate import NewFeature

        feature = NewFeature(config)
        result = await feature.run(code)

  - type: dropdown
    id: component
    attributes:
      label: Related Component
      description: Which component would this feature affect?
      options:
        - ExploitAgent
        - BreakAgent
        - ChaosAgent
        - ChaosOrchestrator
        - Arbiter
        - Sandbox
        - Bead Store
        - Configuration
        - CLI
        - Logging
        - Providers
        - New Component
        - Multiple Components
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Nice to have
        - Would significantly improve my workflow
        - Critical for my use case

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be willing to help implement this feature?
      options:
        - label: I would be willing to submit a PR for this feature
        - label: I would be willing to help test this feature
        - label: I would be willing to help document this feature

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples
      placeholder: Any additional information...
